spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root
    password: "000000"
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user-service-dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.220.159:8848
        access-key: a22b4aed-8233-4fa2-9ced-13222f3a7176
      config:
        server-addr: 192.168.220.159:8848
        access-key: a22b4aed-8233-4fa2-9ced-13222f3a7176
  config:
    import: nacos:application.yaml
#        access-key: a22b4aed-8233-4fa2-9ced-13222f3a7176
#        access-key: a22b4aed-8233-4fa2-9ced-13222f3a7176
#        server-addr: 127.0.0.1:8848


feign:
  okhttp:
    enable: true

server:
  port: 8083
#logging:
#  level:
#    root: debug
